INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, DOCUMENT_NUMBER, PASSWORD) VALUES (1, 'Juan', 'López', '123456789', '$2a$04$GJ85Ihcglhbqac2zc3z3A.C3v55FMmN8.qGQ8FlNBCuyLtQ5/TyMO');
INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, DOCUMENT_NUMBER, PASSWORD) VALUES (2, 'José', 'Gonzalez', '12345678', '$2a$04$XWpgKkCQaVRuXjB5f1hzt.pDa2NAzntroH3bELICZy8R8Q0L0SShO');
INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, DOCUMENT_NUMBER, PASSWORD) VALUES (3, 'Pablo', 'Gómez', '987654321', '$2a$04$bmmWXec6YkFIesIxv2gx7.NbxRcMJ4UoRKT9Qoqk09pKegfcr3Zla');
INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, DOCUMENT_NUMBER, PASSWORD) VALUES (4, 'Franco', 'Acebo Canal', '37654985', '$2a$04$XWpgKkCQaVRuXjB5f1hzt.pDa2NAzntroH3bELICZy8R8Q0L0SShO');


INSERT INTO ROLES (ID, DESCRIPTION, ROLE_NAME) VALUES (1, 'BackOffice role', 'BACKOFFICE');
INSERT INTO ROLES (ID, DESCRIPTION, ROLE_NAME) VALUES (2, 'Client role', 'CLIENT');
INSERT INTO ROLES (ID, DESCRIPTION, ROLE_NAME) VALUES (3, 'Infraestructure role', 'INFRA');

INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (3, 3);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (4, 2);


INSERT INTO RATES (ID, TYPE_RATE, PRICE_KWH) VALUES (1, 'PUBLIC_RATE', 3.53);
INSERT INTO RATES (ID, TYPE_RATE, PRICE_KWH) VALUES (2, 'SOCIAL_RATE', 1.25);
INSERT INTO RATES (ID, TYPE_RATE, PRICE_KWH) VALUES (3, 'GENERAL_RATE', 5.53);
INSERT INTO RATES (ID, TYPE_RATE, PRICE_KWH) VALUES (4, 'ESPECIAL_RATE', 2.75);


-- José Gonzalez  12345678
INSERT INTO ADDRESSES (ID, STREET_NAME, STREET_NUMBER, ZIP_CODE, CITY) VALUES (1, 'Av. Siempre Viva', 742, 7600, 'Mar del Plata');

INSERT INTO ELECTRICAL_METERS (ID, USER_ID, ADDRESS_ID, RATE_ID, SERIAL_NUMBER, BRAND, MODEL) VALUES (1, 2, 1, 1, 'AAA-123', 'Powermeter', 'Smart LED NP150');

-- Franco
INSERT INTO ADDRESSES (ID, STREET_NAME, STREET_NUMBER, ZIP_CODE, CITY) VALUES (2, 'Calle Falsa', 123, 7600, 'Mar del Plata' );
INSERT INTO ADDRESSES (ID, STREET_NAME, STREET_NUMBER, FLOOR, DEPARTMENT, ZIP_CODE, CITY) VALUES (3, 'Av. Colón', 2233, '4', 'C', 7600, 'Mar del Plata');


INSERT INTO ELECTRICAL_METERS (ID, USER_ID, ADDRESS_ID, RATE_ID, SERIAL_NUMBER, BRAND, MODEL) VALUES (2, 4, 2, 3, 'AAB-456', 'Powermeter', 'Smart LED NP150');
INSERT INTO ELECTRICAL_METERS (ID, USER_ID, ADDRESS_ID, RATE_ID, SERIAL_NUMBER, BRAND, MODEL) VALUES (3, 4, 3, 2, 'ABC-789', 'Powermeter', 'Smart LED NP150');


--- mediciones

INSERT INTO ELECTRICAL_MEASUREMENTS (ID, ELECTRICAL_METER_ID, MEASUREMENT_DATE, MEASUREMENT_KWH) VALUES (1, 1, '2021-01-01 00:00:00', 0.0);
INSERT INTO ELECTRICAL_MEASUREMENTS (ID, ELECTRICAL_METER_ID, MEASUREMENT_DATE, MEASUREMENT_KWH)VALUES (2, 1, '2021-01-01 00:05:00', 0.5);
INSERT INTO ELECTRICAL_MEASUREMENTS (ID, ELECTRICAL_METER_ID, MEASUREMENT_DATE, MEASUREMENT_KWH)VALUES (3, 1, '2021-01-01 00:10:00', 1.5);
INSERT INTO ELECTRICAL_MEASUREMENTS (ID, ELECTRICAL_METER_ID, MEASUREMENT_DATE, MEASUREMENT_KWH)VALUES (4, 1, '2021-01-01 00:15:00', 2.0);
