INSERT INTO USERS (ID, FIRST_NAME, DOCUMENT_NUMBER, PASSWORD) VALUES (1, 'Juan', '123456789', '$2a$04$GJ85Ihcglhbqac2zc3z3A.C3v55FMmN8.qGQ8FlNBCuyLtQ5/TyMO');
INSERT INTO USERS (ID, FIRST_NAME, DOCUMENT_NUMBER, PASSWORD) VALUES (2, 'José', '12345678', '$2a$04$XWpgKkCQaVRuXjB5f1hzt.pDa2NAzntroH3bELICZy8R8Q0L0SShO');
INSERT INTO USERS (ID, FIRST_NAME, DOCUMENT_NUMBER, PASSWORD) VALUES (3, 'Pablo', '987654321', '$2a$04$bmmWXec6YkFIesIxv2gx7.NbxRcMJ4UoRKT9Qoqk09pKegfcr3Zla');

INSERT INTO ROLES (ID, DESCRIPTION, ROLE_NAME) VALUES (1, 'BackOffice role', 'BACKOFFICE');
INSERT INTO ROLES (ID, DESCRIPTION, ROLE_NAME) VALUES (2, 'Client role', 'CLIENT');
INSERT INTO ROLES (ID, DESCRIPTION, ROLE_NAME) VALUES (3, 'Infraestructure role', 'INFRA');

INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (3, 3);


/*
    VIEWS
*/

CREATE VIEW v_bills
AS
SELECT

    u.DOCUMENT_NUMBER as documentNumber,
    CONCAT(u.FIRST_NAME,", ",u.LAST_NAME) AS fullName,
    CONCAT(em.BRAND, ", ", em.MODEL, ", ", em.SERIAL_NUMBER) AS electricalMeter,
    CONCAT(a.STREET_NAME, " ", a.STREET_NUMBER, ", ", a.ZIP_CODE, ", ", a.CITY ) AS address,
    r.TYPE_RATE AS rateType,
    r.PRICE AS priceByRate,

    emi.MEASUREMENT_DATE AS measurementDateInitial,
    emi.MEASUREMENT_KWH AS measurementInitial,

    emf.MEASUREMENT_DATE AS measurementDateFinal,
    emf.MEASUREMENT_KWH AS measurementFinal,

    b.EXPIRATION_DATE AS expirationDate,

    (emf.MEASUREMENT_KWH - emi.MEASUREMENT_KWH)  AS measurementTotalKWH,
    (r.PRICE * (emf.MEASUREMENT_KWH - emi.MEASUREMENT_KWH) ) AS totalAmount

    b.IS_PAID AS isPaid

FROM USERS u
         INNER JOIN ELECTRICAL_METERS em ON u.ID = em.ID_USER
         INNER JOIN ADDRESS a ON em.ADDRESS_ID = a.ID
         INNER JOIN BILLS b ON b.ELECTRICAL_METER_ID = em.ID
         INNER JOIN RATES r ON b.RATE_ID = r.ID
         INNER JOIN ELECTRICAL_MEASURMENTS emi ON b.ELECTRICAL_MEASUREMENT_INITIAL_ID = em.ID
         INNER JOIN ELECTRICAL_MEASURMENTS emf ON b.ELECTRICAL_MEASUREMENT_FINAL_ID = em.ID
where  u.IS_ENABLED = true;