INSERT INTO USERS (ID, FIRST_NAME, DOCUMENT_NUMBER, PASSWORD) VALUES (1, 'Juan', '123456789', '$2a$04$GJ85Ihcglhbqac2zc3z3A.C3v55FMmN8.qGQ8FlNBCuyLtQ5/TyMO');
INSERT INTO USERS (ID, FIRST_NAME, DOCUMENT_NUMBER, PASSWORD) VALUES (2, 'José', '12345678', '$2a$04$XWpgKkCQaVRuXjB5f1hzt.pDa2NAzntroH3bELICZy8R8Q0L0SShO');
INSERT INTO USERS (ID, FIRST_NAME, DOCUMENT_NUMBER, PASSWORD) VALUES (3, 'Pablo', '987654321', '$2a$04$XWpgKkCQaVRuXjB5f1hzt.pDa2NAzntroH3bELICZy8R8Q0L0SShO');


INSERT INTO ROLES (ID, DESCRIPTION, ROLE_NAME) VALUES (1, 'BackOffice role', 'BACKOFFICE');
INSERT INTO ROLES (ID, DESCRIPTION, ROLE_NAME) VALUES (2, 'Client role', 'CLIENT');
INSERT INTO ROLES (ID, DESCRIPTION, ROLE_NAME) VALUES (3, 'Infraestructure role', 'INFRA');

INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (3, 3);
